In [4]:
import numpy as np

In [5]:
#1D array
x = np.array([1,2,3,4,5,6])

In [6]:
print(x)

[1 2 3 4 5 6]


In [7]:
#2D array
y = np.array([[1,2,3,4,5,6],[5,10,15,20,25,30]])

In [8]:
#3D array
z = np.array([
        [[1,2,3,4,5,6],[5,10,15,20,25,30]],
        [[2,4,6,8,10,12],[1,3,5,7,9,11]]
    ])

In [9]:
print(y)


[[ 1  2  3  4  5  6]
 [ 5 10 15 20 25 30]]


In [10]:
print(z)

[[[ 1  2  3  4  5  6]
  [ 5 10 15 20 25 30]]

 [[ 2  4  6  8 10 12]
  [ 1  3  5  7  9 11]]]


In [11]:
x.shape


(6,)

In [12]:
y.shape


(2, 6)

In [13]:
z.shape

(2, 2, 6)

In [14]:
type(x)
type(y)
type(z)

numpy.ndarray

In [15]:
z.dtype

dtype('int32')

In [16]:
arr1 = np.array([[2,4,6,8],[4,5,6,1]])
arr2 = np.array([[1,3,5,7],[5,7,2,6]])

In [17]:
sum = arr1 + arr2

In [18]:
print(sum)

[[ 3  7 11 15]
 [ 9 12  8  7]]


In [19]:
arr3 = np.array([[2,4,6,8],[4,5,6,1]])
arr4 = np.array([1,3,5,7])

In [20]:
sum2 = arr3 + arr4

In [21]:
print(sum2)

[[ 3  7 11 15]
 [ 5  8 11  8]]


In [22]:
scal = arr3 * 2
print(scal)

[[ 4  8 12 16]
 [ 8 10 12  2]]


In [23]:
random_num = np.random.rand()

In [24]:
print(random_num)

0.9471399942301141


In [25]:
ran_num2 = np.random.rand(2,5,3)

In [26]:
print(ran_num2)

[[[0.31280344 0.55229031 0.39551603]
  [0.97216537 0.2321696  0.57809357]
  [0.54812433 0.5927369  0.05315306]
  [0.57975767 0.54492529 0.48611061]
  [0.28319488 0.4025894  0.16786732]]

 [[0.44239676 0.22003266 0.40558431]
  [0.81191457 0.39106684 0.50157917]
  [0.30046277 0.36804336 0.59220035]
  [0.88081694 0.71127198 0.43339696]
  [0.0406276  0.16534857 0.67950724]]]


In [27]:
ran_num3 = np.random.uniform(8,99,size=5)
print(ran_num3)

[65.30421352 64.71470953 71.18533543 43.68510223 70.9804928 ]


In [28]:
ran_2d = np.random.randint(3,50,size=(5,3))
print(ran_2d)

[[23 15 46]
 [36 42 31]
 [49 21 18]
 [23 12 48]
 [38 42 46]]


In [29]:
random_num4 = np.random.uniform(3,50,size=(5,3))
print(random_num4)

[[27.9078999  40.8012885   8.701576  ]
 [35.44942338 28.94408878 30.18161894]
 [38.13748431  8.91981738 16.294401  ]
 [20.50504511 29.73012725 28.10252708]
 [32.00641399 41.18562121 39.72272001]]


In [30]:
rounded_array = np.around(random_num4, decimals=1)
print(rounded_array)

[[27.9 40.8  8.7]
 [35.4 28.9 30.2]
 [38.1  8.9 16.3]
 [20.5 29.7 28.1]
 [32.  41.2 39.7]]


In [31]:
print(np.round(random_num4,1))

[[27.9 40.8  8.7]
 [35.4 28.9 30.2]
 [38.1  8.9 16.3]
 [20.5 29.7 28.1]
 [32.  41.2 39.7]]


In [38]:
np.random.seed(42)  # Set a fixed seed value
random_array = np.random.randint(1, 100, size=(3, 4))  # This will generate the same random numbers every time
print(random_array)

[[52 93 15 72]
 [61 21 83 87]
 [75 75 88 24]]


In [47]:
np.random.seed(5)  # Set a fixed seed value
random_array = np.random.randint(1, 100, size=(3, 25))  # This will generate the same random numbers every time
print(random_array)

[[79 62 17 74  9 63 28 31 81  8 77 16 54 81 28 45 78 76 66 48 31 85 87 19
  10]
 [42 63  2 83 17 79  6 59  1 81  5 37 52 28 32  3 69 39 84 20 19  8 31 63
  12]
 [68 66 56  4 92 79 28 30 34 90 86  8 17 95 15 91 32 10 39 48 17  6 35 46
  60]]


In [70]:
np.random.choice(random_array.flatten(), size=7, replace=False)

array([ 6, 78, 54,  8, 59, 79,  5])